markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - repo-metadata.html
  - maintainer-notes.md
  - generate_projects.py
theme: jekyll-theme-cayman
plugins:
  - jekyll-paginate
paginate: 40
paginate_path: "/page:num"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "newsletter"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      layout: "project"
      excerpt_separator: <!--more-->    
  -
    scope:
      path: "newsletters"
      type: "posts"
    values:
      layout: "newsletter"
      excerpt_separator: <!--more-->    
  -
    scope:
      path: "add_project"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "add_newsletter"
      type: "pages"
    values:
      layout: "page"
kramdown:
  toc_levels: "2,3"
  input: GFM
